2010-06-17 : got Qt to build automatically, (or use the binaries) 2010-06-17 : got --enable-vistrails to work and build SIP and PyQt

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -951,6 +951,15 @@ WGET_URL
 WGET_GZ
 HASCURL
 PYINSTALLKEY
+PYTHON_INSTALL_PREFIX
+QT_MAJOR
+QT_MINOR
+QT_PATCH
+QT_MAJOR_SRC
+QT_MINOR_SRC
+QT_PATCH_SRC
+QT_URL
+QT_GZ
 CXX
 CXXFLAGS
 LDFLAGS
@@ -991,6 +1000,7 @@ X_PRE_LIBS
 X_LIBS
 X_EXTRA_LIBS
 COMPILE_VTK
+QTCONFIGOPT
 EXTRAENV
 GREP
 EGREP
@@ -1009,6 +1019,7 @@ QMAKE
 QT_INC
 QT_LIB
 QT_BIN
+BUILDQT
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1628,11 +1639,6 @@ Optional Features:
   --enable-netcdf-fortran enables netcdf-fortran (default is no)
   --enable-all            build all externals
   --enable-qt-debug       adds _debug to Qt libs
-  --enable-qt             use qt instead of tcl/tk default:
-                          /usr/local/Trolltech/Qt-4.5.2/ to change these use
-                          --with-qt/--with-qt-inc/--with-qt-lib/--with-qt-bin
-                          instead
-  --enable-qtframework    use qt framework instead of tcl/tk
   --enable-vistrails      Build extra dependencies that are needed by
                           vistrails
 
@@ -2501,7 +2507,7 @@ XGKS_GZ=xgks.tar.gz
 
 
 JPEG_URL=http://www.ijg.org/files
-JPEG_GZ=jpegsrc.v8a.tar.gz
+JPEG_GZ=jpegsrc.v8b.tar.gz
 
 
 BLAS_URL=http://www.netlib.org/blas
@@ -2697,6 +2703,24 @@ TERMCAP_GZ=termcap-1.3.1.tar.gz
 
 
 
+
+
+PYTHON_INSTALL_PREFIX=""
+
+QT_MAJOR_SRC=4
+QT_MINOR_SRC=6
+QT_PATCH_SRC=3
+QT_MAJOR=4
+QT_MINOR=6
+QT_PATCH=2
+
+
+
+
+
+
+QT_URL=ftp://ftp.qt.nokia.com/qt/source
+QT_GZ=qt-everywhere-opensource-src-${QT_MAJOR_SRC}.${QT_MINOR_SRC}.${QT_PATCH_SRC}.tar.gz
 
 
 
@@ -7370,6 +7394,8 @@ fi
 
 EXTRAENV=""
 
+
+
 { echo "$as_me:$LINENO: add ${EXTERNALS} to LD and CPP FLAGS" >&5
 echo "$as_me: add ${EXTERNALS} to LD and CPP FLAGS" >&6;}
 LDFLAGS="-L${EXTERNALS}/lib  -L${prefix}/lib -L${EXTERNALS}/NetCDF/lib  -L${EXTERNALS}/HDF5/lib "$LDFLAGS
@@ -7408,7 +7434,9 @@ echo "$as_me: adding -L${IC}/lib -Wl,--rpath,${IC}/lib -limf -lirc to LDFLAGS" >
 echo "${ECHO_T}no" >&6; }
   fi ;;
  darwin*)
-  PyQT_PLATFORM="mac"
+  PyQt_PLATFORM="mac"
+  PYOPTXTRAQT=" --enable-qt-framework "
+  QTCONFIGOPT=" -cocoa "
   MD5PRG="md5"
   MD5CNT=4
   LDFLAGS=${LDFLAGS}" -R${prefix}/lib -R${EXTERNALS}/lib  -R${EXTERNALS}/NetCDF/lib  -R${EXTERNALS}/HDF5/lib "
@@ -7466,6 +7494,9 @@ fi
          PYOPT=" --enable-framework=${enable_framework}"
          cp exsrc/src/CMakeCache.txt.mac.Framework.in exsrc/CMakeCache.txt.in
          PYINSTALLKEY="frameworkinstall"
+	 if test ${enable_fw} != "-"${prefix} ; then
+	    PYTHON_INSTALL_PREFIX=" --prefix=${enable_framework} "
+	 fi
      else
        if test ${enable_vtk} == "-yes" ; then
            PYOPT=" --enable-framework=${prefix} "
@@ -7698,11 +7729,12 @@ echo "${ECHO_T}$ac_res" >&6; }
 if test `eval echo '${'$as_ac_File'}'` = yes; then
   PYTHON=${with_python}
 else
-  { { echo "$as_me:$LINENO: error: your python is not here" >&5
-echo "$as_me: error: your python is not here" >&2;}
+  { { echo "$as_me:$LINENO: error: Could not find python executable ${with_python}" >&5
+echo "$as_me: error: Could not find python executable ${with_python}" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+  PYTHON_INSTALL_PREFIX=" --prefix=${with_python} "
 else
   # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
@@ -11618,8 +11650,56 @@ else
   with_qt='no'
 fi
 
+
+BUILDQT="no"
+
+
 if test ${with_qt} != "no" ; then
-   PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --with-qt="${with_qt}
+ { echo "$as_me:$LINENO: WITH QT IS: ${with_qt}" >&5
+echo "$as_me: WITH QT IS: ${with_qt}" >&6;}
+ if test ${with_qt} == "yes" ; then
+   QMAKE=${EXTERNALS}/bin/qmake
+ else
+   QMAKE=${with_qt}/bin/qmake
+ fi
+ as_ac_File=`echo "ac_cv_file_${QMAKE}" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${QMAKE}" >&5
+echo $ECHO_N "checking for ${QMAKE}... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${QMAKE}"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAS_QMAKE=yes
+else
+  HAS_QMAKE=no
+fi
+
+ if test ${HAS_QMAKE} == "no" ; then
+   { echo "$as_me:$LINENO: WARNING: Could not find qmake at ${QMAKE} will build Qt for you" >&5
+echo "$as_me: WARNING: Could not find qmake at ${QMAKE} will build Qt for you" >&2;}
+   BUILDQT="yes"
+   PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}${PYOPTXTRAQT}" --with-qt="${EXTERNALS}
+   QMAKE=${EXTERNALS}/bin/qmake
+ else
+  if test ${with_qt} == "yes" ; then
+   PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}${PYOPTXTRAQT}" --with-qt="${EXTERNALS}
+  else
+   PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}${PYOPTXTRAQT}" --with-qt="${with_qt}
+  fi
+ fi
 else
 
 # Check whether --with-qt-lib was given.
@@ -11652,9 +11732,43 @@ else
 fi
 
   if test ${with_qt_bin} != "no" ; then
-     PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --with-qt-bin="${with_qt_bin}
-  fi;
-fi;
+     QMAKE=${with_qt_bin}/qmake
+     as_ac_File=`echo "ac_cv_file_${QMAKE}" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${QMAKE}" >&5
+echo $ECHO_N "checking for ${QMAKE}... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${QMAKE}"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAS_QMAKE=yes
+else
+  HAS_QMAKE=no
+fi
+
+     if test ${HAS_QMAKE} == "no" ; then
+       { echo "$as_me:$LINENO: WARNING: Could not find qmake at ${QMAKE} will build Qt for you" >&5
+echo "$as_me: WARNING: Could not find qmake at ${QMAKE} will build Qt for you" >&2;}
+       BUILDQT="yes"
+       PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}${PYOPTXTRAQT}" --with-qt="${EXTERNALS}
+       QMAKE=${EXTERNALS}/bin/qmake
+     else
+       PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}${PYOPTXTRAQT}" --with-qt-bin="${with_qt_bin}
+     fi
+  fi
+fi
 # Check whether --enable-qt-debug was given.
 if test "${enable_qt_debug+set}" = set; then
   enableval=$enable_qt_debug;
@@ -11666,33 +11780,6 @@ enble_qtdbg="-"${enable_qt_debug}
 if test ${enble_qtdbg} == "-yes" ; then
      PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --qt-debug"
 fi;
-# Check whether --enable-qt was given.
-if test "${enable_qt+set}" = set; then
-  enableval=$enable_qt;
-else
-  enable_qt='no'
-fi
-
-enble_qt="-"${enable_qt}
-if test ${enble_qt} == "-yes" ; then
-   if test ${enable_fw} == "-yes" ; then
-     PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --enable-qt-framework"
-   else
-     PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --enable-qt"
-   fi;
-fi;
-# Check whether --enable-qt-framework was given.
-if test "${enable_qt_framework+set}" = set; then
-  enableval=$enable_qt_framework;
-else
-  enable_qt_framework='no'
-fi
-
-enble_qtfw="-"${enable_qt_framework}
-if test ${enble_qtfw} == "-yes" ; then
-     PYTHON_INSTALL_OPTIONS=${PYTHON_INSTALL_OPTIONS}" --enable-qt-framework"
-fi;
-
 
 
 # Check whether --enable-vistrails was given.
@@ -11702,15 +11789,15 @@ fi
 
 
 BUILDVIS="no"
-vistr="_"+${enable_vistrails}
+vistr="-"${enable_vistrails}
 if test ${vistr} == "-yes" ; then
   BUILDVIS="yes"
-  if test ${enable_fw} == "-" -o test ${enable_vtk} == "-" ; then
+  if test ${enable_fw} == "-" -a ${enable_vtk} == "-" ; then
      { { echo "$as_me:$LINENO: error: \"You need to enable framework for vistrails\"" >&5
 echo "$as_me: error: \"You need to enable framework for vistrails\"" >&2;}
    { (exit 1); exit 1; }; }
   fi
-  if test "-"${with_qt} == "-" -o test ${enable_vtk} == "-" ; then
+  if test "-"${with_qt} == "-" -a ${enable_vtk} == "-" ; then
      { { echo "$as_me:$LINENO: error: \"You need to enable framework for vistrails\"" >&5
 echo "$as_me: error: \"You need to enable framework for vistrails\"" >&2;}
    { (exit 1); exit 1; }; }
@@ -12816,6 +12903,15 @@ WGET_URL!$WGET_URL$ac_delim
 WGET_GZ!$WGET_GZ$ac_delim
 HASCURL!$HASCURL$ac_delim
 PYINSTALLKEY!$PYINSTALLKEY$ac_delim
+PYTHON_INSTALL_PREFIX!$PYTHON_INSTALL_PREFIX$ac_delim
+QT_MAJOR!$QT_MAJOR$ac_delim
+QT_MINOR!$QT_MINOR$ac_delim
+QT_PATCH!$QT_PATCH$ac_delim
+QT_MAJOR_SRC!$QT_MAJOR_SRC$ac_delim
+QT_MINOR_SRC!$QT_MINOR_SRC$ac_delim
+QT_PATCH_SRC!$QT_PATCH_SRC$ac_delim
+QT_URL!$QT_URL$ac_delim
+QT_GZ!$QT_GZ$ac_delim
 CXX!$CXX$ac_delim
 CXXFLAGS!$CXXFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -12856,18 +12952,9 @@ X_PRE_LIBS!$X_PRE_LIBS$ac_delim
 X_LIBS!$X_LIBS$ac_delim
 X_EXTRA_LIBS!$X_EXTRA_LIBS$ac_delim
 COMPILE_VTK!$COMPILE_VTK$ac_delim
+QTCONFIGOPT!$QTCONFIGOPT$ac_delim
 EXTRAENV!$EXTRAENV$ac_delim
 GREP!$GREP$ac_delim
-EGREP!$EGREP$ac_delim
-HAVE_CMAKE!$HAVE_CMAKE$ac_delim
-FFMPEG!$FFMPEG$ac_delim
-GS!$GS$ac_delim
-PS2EPSI!$PS2EPSI$ac_delim
-GIFSICLE!$GIFSICLE$ac_delim
-PNMFLIP!$PNMFLIP$ac_delim
-PNMCROP!$PNMCROP$ac_delim
-PPMTOGIF!$PPMTOGIF$ac_delim
-FLTK2_CONF!$FLTK2_CONF$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -12909,17 +12996,28 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+EGREP!$EGREP$ac_delim
+HAVE_CMAKE!$HAVE_CMAKE$ac_delim
+FFMPEG!$FFMPEG$ac_delim
+GS!$GS$ac_delim
+PS2EPSI!$PS2EPSI$ac_delim
+GIFSICLE!$GIFSICLE$ac_delim
+PNMFLIP!$PNMFLIP$ac_delim
+PNMCROP!$PNMCROP$ac_delim
+PPMTOGIF!$PPMTOGIF$ac_delim
+FLTK2_CONF!$FLTK2_CONF$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 LOCNCCONFIG!$LOCNCCONFIG$ac_delim
 QMAKE!$QMAKE$ac_delim
 QT_INC!$QT_INC$ac_delim
 QT_LIB!$QT_LIB$ac_delim
 QT_BIN!$QT_BIN$ac_delim
+BUILDQT!$BUILDQT$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 19; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -13456,6 +13554,13 @@ else
     { echo "$as_me:$LINENO: libnetcdf >=4 found at ${NC4LOC}" >&5
 echo "$as_me: libnetcdf >=4 found at ${NC4LOC}" >&6;}
 fi
+if test ${BUILDQT} == "yes" ; then
+    { echo "$as_me:$LINENO: Qt libraries not found... building library ${QT_MAJOR_SRC}.${QT_MINOR_SRC}.${QT_PATCH_SRC}" >&5
+echo "$as_me: Qt libraries not found... building library ${QT_MAJOR_SRC}.${QT_MINOR_SRC}.${QT_PATCH_SRC}" >&6;}
+else
+    { echo "$as_me:$LINENO: Qt > ${QT_MAJOR}.${QT_MINOR}.${QT_PATCH} found or not needed in this configuration" >&5
+echo "$as_me: Qt > ${QT_MAJOR}.${QT_MINOR}.${QT_PATCH} found or not needed in this configuration" >&6;}
+fi
 { echo "$as_me:$LINENO: " >&5
 echo "$as_me: " >&6;}
 { echo "$as_me:$LINENO: ........................................................................" >&5
@@ -13530,26 +13635,13 @@ else
 echo "$as_me: Pmw >= ${PMW_MAJOR}.${PMW_MINOR} found" >&6;}
 fi
 if test ${with_qt} != "no" ; then
-  { echo "$as_me:$LINENO: Will build with QT support" >&5
-echo "$as_me: Will build with QT support" >&6;}
-fi
-if test ${with_qt_lib} != "no" ; then
-  { echo "$as_me:$LINENO: Will build with QT support" >&5
-echo "$as_me: Will build with QT support" >&6;}
-fi
-if test ${enble_qt} == "-yes" ; then
-   if test ${enable_fw} == "-yes" ; then
-     { echo "$as_me:$LINENO: Will build with Framework QT support" >&5
-echo "$as_me: Will build with Framework QT support" >&6;}
-   else
-     { echo "$as_me:$LINENO: Will build with QT support" >&5
-echo "$as_me: Will build with QT support" >&6;}
-   fi
+  { echo "$as_me:$LINENO: Will build with Qt support" >&5
+echo "$as_me: Will build with Qt support" >&6;}
 else
-  if test ${enble_qtfw} == "-yes" ; then
-     { echo "$as_me:$LINENO: Will build with Framework QT support" >&5
-echo "$as_me: Will build with Framework QT support" >&6;}
-  fi
+ if test ${with_qt_bin} != "no"; then
+  { echo "$as_me:$LINENO: Will build with Qt support" >&5
+echo "$as_me: Will build with Qt support" >&6;}
+ fi
 fi
 { echo "$as_me:$LINENO: " >&5
 echo "$as_me: " >&6;}
