addressed @remram44 suggestion
adds a message when UVCDAT was already sourced at the current location

diff --git a/CMake/cdat_modules_extra/setup_runtime.sh.in b/CMake/cdat_modules_extra/setup_runtime.sh.in
--- a/CMake/cdat_modules_extra/setup_runtime.sh.in
+++ b/CMake/cdat_modules_extra/setup_runtime.sh.in
@@ -10,10 +10,11 @@ function cleanup {
 # which can lead to errors.
 if [ -n "${UVCDAT_SETUP_PATH}" ] ; then
   if [ "${UVCDAT_SETUP_PATH}" = "${install_prefix}" ] ; then
+    echo "Nothing to do UVCDAT is already setup at "${UVCDAT_SETUP_PATH} 1>&2
     cleanup
     return 0
   else
-    echo "ERROR: UVCDAT setup was previously sourced at \"${UVCDAT_SETUP_PATH}\"" 1>&2
+    echo "ERROR: UVCDAT setup was previously sourced at "${UVCDAT_SETUP_PATH} 1>&2
     echo "ERROR: There is no need to run setup_runtime manually anymore." 1>&2
     echo "ERROR: Open a new shell in order to use a different install location." 1>&2
     cleanup
@@ -85,8 +86,8 @@ export PYTHONPATH
 
 export UVCDAT_SETUP_PATH="${install_prefix}"
 cleanup
-echo "Successfully updated your environment to use UV-CDAT"
-echo "(changes are valid for this session/terminal only)"
-echo "Version: "${UVCDAT_PROMPT_STRING}
-echo "Location: "${UVCDAT_SETUP_PATH}
+echo "Successfully updated your environment to use UV-CDAT" 1>&2
+echo "(changes are valid for this session/terminal only)" 1>&2
+echo "Version: "${UVCDAT_PROMPT_STRING} 1>&2
+echo "Location: "${UVCDAT_SETUP_PATH} 1>&2
 return 0
