first pass at fix #1852 creating an env reset file

diff --git a/CMake/cdat_modules_extra/setup_runtime.sh.in b/CMake/cdat_modules_extra/setup_runtime.sh.in
--- a/CMake/cdat_modules_extra/setup_runtime.sh.in
+++ b/CMake/cdat_modules_extra/setup_runtime.sh.in
@@ -17,6 +17,7 @@ if [ -n "${UVCDAT_SETUP_PATH}" ] ; then
     echo "ERROR: UVCDAT setup was previously sourced at: ${UVCDAT_SETUP_PATH}" 1>&2
     echo "ERROR: There is no need to run setup_runtime manually anymore." 1>&2
     echo "ERROR: Open a new shell in order to use a different install location." 1>&2
+    echo "ERROR: Or execute reset_runtime.sh." 1>&2
     cleanup
     return 1
   fi
