reverted from INFO to ERROR because we fail to do what user asked in this case

diff --git a/CMake/cdat_modules_extra/setup_runtime.csh.in b/CMake/cdat_modules_extra/setup_runtime.csh.in
--- a/CMake/cdat_modules_extra/setup_runtime.csh.in
+++ b/CMake/cdat_modules_extra/setup_runtime.csh.in
@@ -25,10 +25,10 @@ if ( $?UVCDAT_SETUP_PATH ) then
     echo 'Nothing to do since UVCDAT is already setup at '${UVCDAT_SETUP_PATH}
     exit 0
   else
-    echo 'INFO: UVCDAT setup was previously sourced at '${UVCDAT_SETUP_PATH}
-    echo 'INFO: There is no need to run setup_runtime manually anymore.'
-    echo 'INFO: Open a new shell in order to use a different install location.'
-    exit 0
+    echo 'ERROR: UVCDAT setup was previously sourced at '${UVCDAT_SETUP_PATH}
+    echo 'ERROR: There is no need to run setup_runtime manually anymore.'
+    echo 'ERROR: Open a new shell in order to use a different install location.'
+    exit 1
   endif
 endif
 
diff --git a/CMake/cdat_modules_extra/setup_runtime.sh.in b/CMake/cdat_modules_extra/setup_runtime.sh.in
--- a/CMake/cdat_modules_extra/setup_runtime.sh.in
+++ b/CMake/cdat_modules_extra/setup_runtime.sh.in
@@ -14,11 +14,11 @@ if [ -n "${UVCDAT_SETUP_PATH}" ] ; then
     cleanup
     return 0
   else
-    echo "INFO: UVCDAT setup was previously sourced at: ${UVCDAT_SETUP_PATH}" 1>&2
-    echo "INFO: There is no need to run setup_runtime manually anymore." 1>&2
-    echo "INFO: Open a new shell in order to use a different install location." 1>&2
+    echo "ERROR: UVCDAT setup was previously sourced at: ${UVCDAT_SETUP_PATH}" 1>&2
+    echo "ERROR: There is no need to run setup_runtime manually anymore." 1>&2
+    echo "ERROR: Open a new shell in order to use a different install location." 1>&2
     cleanup
-    return 0
+    return 1
   fi
 fi
 
